# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2c764096b69a033e858303f6f0e3a3792ba80e8b1de2f578928a79459bf26cd0ef4b46c2a92b8170dc166cfc1a1f1ae45e8e56d68900f3e423fa2ca16c1ec6b

test:
  secret_key_base: 0570c7c3359412f728c113d3cbafa1df26fda1a74adcafa40aced462e5f771b8f883dbabd8ed37e30b1dd2564feee661765f3821e937bf3b52d7a6c04f34ffec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
